# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  workflow_dispatch:
    inputs:
      versioncode:
        description: 'Version Code'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      # 改进的 Python 虚拟环境缓存
      - name: Cache Python virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          # 使用固定依赖列表作为缓存键的一部分
          key: ${{ runner.os }}-venv-ifo-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-venv-ifo
            ${{ runner.os }}-venv-

      # 创建依赖清单文件
      - name: Create package list
        run: |
          echo "pyglossary" > packages.txt
          echo "PyICU" >> packages.txt
          echo "lxml" >> packages.txt
          echo "prompt_toolkit" >> packages.txt

      # Install system dependencies and Python packages if cache miss
      - name: install
        run: |
          if [ ! -d ".venv" ]; then
            echo "Creating new virtual environment..."
            uv venv
          fi
          source .venv/bin/activate
          
          # 检查是否需要安装系统依赖
          if ! dpkg -l | grep -q "libicu-dev"; then
            echo "Installing system dependencies..."
            sudo apt-get update
            sudo apt-get install -y pkg-config libicu-dev
          fi
          
          # 检查是否需要安装Python包
          if ! pip list | grep -q "pyglossary"; then
            echo "Installing Python packages..."
            uv pip install -r packages.txt
          fi
          
          mkdir -p output

      # Cache the downloaded slob file
      - name: Cache slob file
        id: cache-slob
        uses: actions/cache@v4
        with:
          path: zhwiki-${{ github.event.inputs.versioncode }}.slob
          # 使用更简单的缓存键
          key: slob-file-${{ github.event.inputs.versioncode }}
          restore-keys: |
            slob-file-${{ github.event.inputs.versioncode }}

      # Only download if not cached
      - name: wget
        if: steps.cache-slob.outputs.cache-hit != 'true'
        run: wget -c https://ftp.halifax.rwth-aachen.de/aarddict/zhwiki/zhwiki${{ github.event.inputs.versioncode }}-slob/zhwiki-20250201.slob

      - name: Convert IFO
        run: |
          source .venv/bin/activate
          uv run pyglossary --no-interactive zhwiki-${{ github.event.inputs.versioncode }}.slob output/zhwiki-${{ github.event.inputs.versioncode }}.ifo

      - name: Upload IFO output
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.format }}
          path: output/zhwiki-${{ github.event.inputs.versioncode }}.ifo
          retention-days: 90
